=== CGI-IUGS/HollowWorld/trunk/HollowWorld/ShapeChangeConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.interactive-instruments.de/ShapeChange" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:sc="http://www.interactive-instruments.de/ShapeChange" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<element name="ShapeChangeConfiguration" type="sc:ShapeChangeConfigurationType"/>
	<complexType name="ShapeChangeConfigurationType">
		<sequence>
			<element name="stereotypeAliases">
				<complexType>
					<sequence minOccurs="0" maxOccurs="unbounded">
						<element name="StereotypeAlias" type="sc:StereotypeAliasType"/>
					</sequence>
				</complexType>
			</element>
			<element name="namespaces">
				<complexType>
					<sequence minOccurs="0" maxOccurs="unbounded">
						<element name="Namespace" type="sc:NamespaceType"/>
					</sequence>
				</complexType>
			</element>
			<element name="mapEntries">
				<complexType>
					<choice minOccurs="0" maxOccurs="unbounded">
						<element name="TypeMapEntry" type="sc:MapEntryType"/>
						<element name="BaseMapEntry" type="sc:MapEntryType"/>
						<element name="ElementMapEntry" type="sc:MapEntryType"/>
					</choice>
				</complexType>
			</element>
		</sequence>
	</complexType>
	<complexType name="StereotypeAliasType">
		<sequence/>
		<attribute name="wellknown" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value=""/>
					<enumeration value="Abstract"/>
					<enumeration value="DataType"/>
					<enumeration value="FeatureType"/>
					<enumeration value="ObjectType"/>
					<enumeration value="Enumeration"/>
					<enumeration value="CodeList"/>
					<enumeration value="Union"/>
					<enumeration value="BasicType"/>
					<enumeration value="Interface"/>
					<enumeration value="Type"/>
					<enumeration value="Union"/>
					<enumeration value="FeatureCollection"/>
					<enumeration value="Application Schema"/>
					<enumeration value="Leaf"/>
					<enumeration value="import"/>
					<enumeration value="disjoint"/>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="alias" type="string" use="required"/>
	</complexType>
	<complexType name="NamespaceType">
		<sequence/>
		<attribute name="nsabr" type="string" use="required"/>
		<attribute name="ns" type="string" use="required"/>
		<attribute name="gmlVersion" type="string" use="required"/>
		<attribute name="location" type="string" use="required"/>
	</complexType>
	<complexType name="MapEntryType">
		<sequence/>
		<attribute name="type" type="string" use="required"/>
		<attribute name="gmlVersion" type="string" use="required"/>
		<attribute name="rule" type="string" use="required"/>
		<attribute name="mapTo" type="string" use="required"/>
		<attribute name="nsabr" type="string"/>
	</complexType>
</schema>

=== CGI-IUGS/HollowWorld/trunk/HollowWorld/ShapeChangeConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<ShapeChangeConfiguration xmlnsabr="http://www.interactive-instruments.de/ShapeChange" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.interactive-instruments.de/ShapeChange ShapeChangeConfiguration.xsd">
	<stereotypeAliases>
		<StereotypeAlias wellknown="DataType" alias="Request"/>
		<StereotypeAlias wellknown="DataType" alias="Response"/>
		<StereotypeAlias wellknown="FeatureType" alias="Feature"/>
	</stereotypeAliases>
	<namespaces>
		<Namespace nsabr="sc" ns="http://www.interactive-instruments.de/ShapeChange" gmlVersion="*" location="http://www.interactive-instruments.de/ShapeChange/ShapeChangeAppinfo.xsd"/>
		<Namespace nsabr="xlink" ns="http://www.w3.org/1999/xlink" gmlVersion="2.1" location="http://schemas.opengis.net/gml/2.1.2/xlinks.xsd"/>
		<Namespace nsabr="gml" ns="http://www.opengis.net/gml" gmlVersion="2.1" location="http://schemas.opengis.net/gml/2.1.2/feature.xsd"/>
		<Namespace nsabr="xlink" ns="http://www.w3.org/1999/xlink" gmlVersion="3.0" location="http://schemas.opengis.net/gml/3.0.1/xlink/xlinks.xsd"/>
		<Namespace nsabr="gml" ns="http://www.opengis.net/gml" gmlVersion="3.0" location="http://schemas.opengis.net/gml/3.0.1/base/gml.xsd"/>
		<Namespace nsabr="xlink" ns="http://www.w3.org/1999/xlink" gmlVersion="3.1" location="http://schemas.opengis.net/gml/3.1.0/xlink/xlinks.xsd"/>
		<Namespace nsabr="gml" ns="http://www.opengis.net/gml" gmlVersion="3.1" location="http://schemas.opengis.net/gml/3.1.1/base/gml.xsd"/>
		<!--
		<Namespace nsabr="scXML" ns="http://www.isotc211.org/scXML" gmlVersion="3.1" location="http://www.isotc211.org/scXML/scXMLbase.xsd"/>
		<Namespace nsabr="smXML" ns="http://www.isotc211.org/smXML" gmlVersion="3.1" location="http://www.isotc211.org/smXML/metadataEntity.xsd"/>
		-->
		<!-- SEE Grid - Hollow World template -->
		<Namespace nsabr="geo" ns="http://www.seegrid.csiro.au/xml/geometry" gmlVersion="*" location="https://www.seegrid.csiro.au/subversion/xmml/trunk/geo/0.1.0/geo.xsd"/>
		<Namespace nsabr="meta" ns="http://www.seegrid.csiro.au/xml/metaLite" gmlVersion="*" location="https://www.seegrid.csiro.au/subversion/xmml/trunk/metaLite/0.1.30/metaLite.xsd"/>
		<Namespace nsabr="sa" ns="http://www.seegrid.csiro.au/xml/sampling" gmlVersion="*" location="https://www.seegrid.csiro.au/subversion/xmml/trunk/sampling/0.1.0/sampling.xsd"/>
		<Namespace nsabr="swe" ns="http://www.opengis.net/swe" gmlVersion="*" location="https://www.seegrid.csiro.au/subversion/xmml/trunk/sweCommon/1.0.30/swe.xsd"/>
		<Namespace nsabr="om" ns="http://www.opengis.net/om" gmlVersion="*" location="https://www.seegrid.csiro.au/subversion/xmml/trunk/om/1.0.30/om.xsd"/>
		<Namespace nsabr="" ns="http://www.w3.org/2001/XMLSchema" gmlVersion="*"/>

	</namespaces>
	<mapEntries>
		<!-- ISO/TS 19103 -->
		<!--
		<BaseMapEntry type="Record" gmlVersion="*" rule="direct" mapTo="Record_Type" nsabr="scXML"/>
		<BaseMapEntry type="RecordType" gmlVersion="*" rule="direct" mapTo="RecordType_Type" nsabr="scXML"/>
		<ElementMapEntry type="Record" gmlVersion="*" rule="direct" mapTo="Record" nsabr="scXML"/>
		<ElementMapEntry type="RecordType" gmlVersion="*" rule="direct" mapTo="RecordType" nsabr="scXML"/>
		-->
		<!-- added by SJDC 2005-11-21 -->
	  	<TypeMapEntry type="Any" gmlVersion="*" rule="direct" mapTo="anyType"/>
	  	<!-- ............... -->
		<TypeMapEntry type="Angle" gmlVersion="3.0" rule="direct" mapTo="AngleType" nsabr="gml"/>
		<TypeMapEntry type="Angle" gmlVersion="3.1" rule="direct" mapTo="AngleType" nsabr="gml"/>
		<TypeMapEntry type="Area" gmlVersion="3.0" rule="direct" mapTo="AreaType" nsabr="gml"/>
		<TypeMapEntry type="Area" gmlVersion="3.1" rule="direct" mapTo="AreaType" nsabr="gml"/>
		<TypeMapEntry type="Boolean" gmlVersion="*" rule="direct" mapTo="boolean"/>
		<TypeMapEntry type="CharacterString" gmlVersion="*" rule="direct" mapTo="string"/>
		<TypeMapEntry type="Date" gmlVersion="*" rule="direct" mapTo="date"/>
		<TypeMapEntry type="DateTime" gmlVersion="*" rule="direct" mapTo="dateTime"/>
		<TypeMapEntry type="Decimal" gmlVersion="*" rule="direct" mapTo="double"/>
		<TypeMapEntry type="Distance" gmlVersion="3.0" rule="direct" mapTo="LengthType" nsabr="gml"/>
		<TypeMapEntry type="Distance" gmlVersion="3.1" rule="direct" mapTo="LengthType" nsabr="gml"/>
		<TypeMapEntry type="GenericName" gmlVersion="2.1.2" rule="direct" mapTo="string"/>
		<TypeMapEntry type="GenericName" gmlVersion="3.0" rule="direct" mapTo="CodeType" nsabr="gml"/>
		<TypeMapEntry type="GenericName" gmlVersion="3.1" rule="direct" mapTo="CodeType" nsabr="gml"/>
		<TypeMapEntry type="Integer" gmlVersion="*" rule="direct" mapTo="integer"/>
		<TypeMapEntry type="Length" gmlVersion="3.0" rule="direct" mapTo="LengthType" nsabr="gml"/>
		<TypeMapEntry type="Length" gmlVersion="3.1" rule="direct" mapTo="LengthType" nsabr="gml"/>
		<TypeMapEntry type="LocalName" gmlVersion="2.1.2" rule="direct" mapTo="string"/>
		<TypeMapEntry type="LocalName" gmlVersion="3.0" rule="direct" mapTo="CodeType" nsabr="gml"/>
		<TypeMapEntry type="LocalName" gmlVersion="3.1" rule="direct" mapTo="CodeType" nsabr="gml"/>
		<TypeMapEntry type="Measure" gmlVersion="3.0" rule="direct" mapTo="MeasureType" nsabr="gml"/>
		<TypeMapEntry type="Measure" gmlVersion="3.1" rule="direct" mapTo="MeasureType" nsabr="gml"/>
		<TypeMapEntry type="Number" gmlVersion="*" rule="direct" mapTo="double"/>
		<TypeMapEntry type="Real" gmlVersion="*" rule="direct" mapTo="double"/>
		<!--
		<TypeMapEntry type="Record" gmlVersion="*" rule="propertyType" mapTo="Record" nsabr="scXML"/>
		<TypeMapEntry type="RecordType" gmlVersion="*" rule="propertyType" mapTo="RecordType" nsabr="scXML"/>
		-->
		<TypeMapEntry type="Scale" gmlVersion="3.0" rule="direct" mapTo="ScaleType" nsabr="gml"/>
		<TypeMapEntry type="Scale" gmlVersion="3.1" rule="direct" mapTo="ScaleType" nsabr="gml"/>
		<!--
		<TypeMapEntry type="ScopedName" gmlVersion="3.0" rule="direct" mapTo="CodeType" nsabr="gml"/>
		<TypeMapEntry type="ScopedName" gmlVersion="3.1" rule="direct" mapTo="CodeType" nsabr="gml"/>
		-->
		<TypeMapEntry type="Time" gmlVersion="*" rule="direct" mapTo="time"/>
		<TypeMapEntry type="UnitOfMeasure" gmlVersion="3.0" rule="direct" mapTo="UnitOfMeasureType" nsabr="gml"/>
		<TypeMapEntry type="UnitOfMeasure" gmlVersion="3.1" rule="direct" mapTo="UnitOfMeasureType" nsabr="gml"/>
		<TypeMapEntry type="Vector" gmlVersion="2.1.2" rule="direct" mapTo="CoordinatesType" nsabr="gml"/>
		<TypeMapEntry type="Vector" gmlVersion="3.0" rule="direct" mapTo="VectorType" nsabr="gml"/>
		<TypeMapEntry type="Vector" gmlVersion="3.1" rule="direct" mapTo="VectorType" nsabr="gml"/>
		<TypeMapEntry type="Velocity" gmlVersion="3.0" rule="direct" mapTo="VelocityType" nsabr="gml"/>
		<TypeMapEntry type="Velocity" gmlVersion="3.1" rule="direct" mapTo="SpeedType" nsabr="gml"/>
		<TypeMapEntry type="Volume" gmlVersion="3.0" rule="direct" mapTo="VolumeType" nsabr="gml"/>
		<TypeMapEntry type="Volume" gmlVersion="3.1" rule="direct" mapTo="VolumeType" nsabr="gml"/>
		<TypeMapEntry type="Year" gmlVersion="*" rule="direct" mapTo="gYear"/>
		<!-- ISO 19107 Geometry -->
		<BaseMapEntry type="GM_Aggregate" gmlVersion="2.1.2" rule="direct" mapTo="MultiGeometryType" nsabr="gml"/>
		<BaseMapEntry type="GM_Aggregate" gmlVersion="3.0" rule="direct" mapTo="MultiGeometryType" nsabr="gml"/>
		<BaseMapEntry type="GM_Aggregate" gmlVersion="3.1" rule="direct" mapTo="MultiGeometryType" nsabr="gml"/>
		<BaseMapEntry type="GM_Complex" gmlVersion="3.0" rule="direct" mapTo="GeometricComplexType" nsabr="gml"/>
		<BaseMapEntry type="GM_Complex" gmlVersion="3.1" rule="direct" mapTo="GeometricComplexType" nsabr="gml"/>
		<BaseMapEntry type="GM_CompositeCurve" gmlVersion="3.0" rule="direct" mapTo="CompositeCurve" nsabr="gml"/>
		<BaseMapEntry type="GM_CompositeCurve" gmlVersion="3.1" rule="direct" mapTo="CompositeCurve" nsabr="gml"/>
		<BaseMapEntry type="GM_CompositePoint" gmlVersion="3.0" rule="direct" mapTo="PointType" nsabr="gml"/>
		<BaseMapEntry type="GM_CompositePoint" gmlVersion="3.1" rule="direct" mapTo="PointType" nsabr="gml"/>
		<BaseMapEntry type="GM_CompositeSolid" gmlVersion="3.0" rule="direct" mapTo="CompositeSolid" nsabr="gml"/>
		<BaseMapEntry type="GM_CompositeSolid" gmlVersion="3.1" rule="direct" mapTo="CompositeSolid" nsabr="gml"/>
		<BaseMapEntry type="GM_CompositeSurface" gmlVersion="3.0" rule="direct" mapTo="CompositeSurface" nsabr="gml"/>
		<BaseMapEntry type="GM_CompositeSurface" gmlVersion="3.1" rule="direct" mapTo="CompositeSurface" nsabr="gml"/>
		<BaseMapEntry type="GM_Curve" gmlVersion="2.1.2" rule="direct" mapTo="LineStringType" nsabr="gml"/>
		<BaseMapEntry type="GM_Curve" gmlVersion="3.0" rule="direct" mapTo="AbstractCurveType" nsabr="gml"/>
		<BaseMapEntry type="GM_Curve" gmlVersion="3.1" rule="direct" mapTo="AbstractCurveType" nsabr="gml"/>
		<BaseMapEntry type="GM_Envelope" gmlVersion="3.0" rule="direct" mapTo="Envelope" nsabr="gml"/>
		<BaseMapEntry type="GM_Envelope" gmlVersion="3.1" rule="direct" mapTo="Envelope" nsabr="gml"/>
		<BaseMapEntry type="GM_MultiCurve" gmlVersion="2.1.2" rule="direct" mapTo="MultiLineStringType" nsabr="gml"/>
		<BaseMapEntry type="GM_MultiCurve" gmlVersion="3.0" rule="direct" mapTo="MultiCurveType" nsabr="gml"/>
		<BaseMapEntry type="GM_MultiCurve" gmlVersion="3.1" rule="direct" mapTo="MultiCurveType" nsabr="gml"/>
		<BaseMapEntry type="GM_MultiPoint" gmlVersion="2.1.2" rule="direct" mapTo="MultiPointType" nsabr="gml"/>
		<BaseMapEntry type="GM_MultiPoint" gmlVersion="3.0" rule="direct" mapTo="MultiPointType" nsabr="gml"/>
		<BaseMapEntry type="GM_MultiPoint" gmlVersion="3.1" rule="direct" mapTo="MultiPointType" nsabr="gml"/>
		<BaseMapEntry type="GM_MultiPrimitive" gmlVersion="2.1.2" rule="direct" mapTo="MultiGeometryType" nsabr="gml"/>
